// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SachkovTech.Infrastructure;

#nullable disable

namespace SachkovTech.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816193646_UpdateExerciseIdToStronglyTyped")]
    partial class UpdateExerciseIdToStronglyTyped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SachkovTech.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("SachkovTech.Domain.Exercises.ExerciseType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("exercise_types", (string)null);
                });

            modelBuilder.Entity("SachkovTech.Domain.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("todo_items", (string)null);
                });

            modelBuilder.Entity("SachkovTech.Domain.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("SachkovTech.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ExerciseType", "SachkovTech.Domain.Workouts.WorkoutExercise.ExerciseType#WorkoutExerciseType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid")
                                .HasColumnName("exercise_id");

                            b1.Property<Guid>("ExerciseTypeId")
                                .HasColumnType("uuid")
                                .HasColumnName("exercise_type_id");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("SachkovTech.Domain.Exercises.Exercise", b =>
                {
                    b.HasOne("SachkovTech.Domain.Exercises.ExerciseType", null)
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SachkovTech.Domain.Workout", b =>
                {
                    b.OwnsOne("SachkovTech.Domain.Workouts.ValueObjects.TagsList", "Tags", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.HasKey("WorkoutId");

                            b1.ToTable("workouts");

                            b1
                                .ToJson("tags")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("SachkovTech.Domain.Workouts.ValueObjects.Tag", "Items", b2 =>
                                {
                                    b2.Property<Guid>("TagsListWorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)");

                                    b2.HasKey("TagsListWorkoutId", "__synthesizedOrdinal");

                                    b2.ToTable("workouts");

                                    b2.WithOwner()
                                        .HasForeignKey("TagsListWorkoutId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Tags")
                        .IsRequired();
                });

            modelBuilder.Entity("SachkovTech.Domain.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("SachkovTech.Domain.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SachkovTech.Domain.Exercises.ExerciseType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("SachkovTech.Domain.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
